language: python
python:
  - "2.6"
  - "2.7"
env:
#  - DJANGO=1.3.4
#  - DJANGO=https://github.com/django/django/zipball/master
install:
#  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python setup_test_buildout.py
  - ./bin/buildout
  - ./bin/test-fixture
